//********************************************************************
//*    	
//* Warning: This file was generated by MDE4CPP Generator
//*
//********************************************************************

#ifndef CLINICMODEL_ADMINISTRATIONFACILITY__HPP
#define CLINICMODEL_ADMINISTRATIONFACILITY__HPP

template<class T> class Bag;



//Forward declarations for used types
namespace ClinicModel 
{
	class Staff;
}

// base class includes
#include "ClinicModel/Facility.hpp"



namespace ClinicModel
{
	class AdministrationFacility:virtual public Facility	{
		protected:
			AdministrationFacility(){}

		public:
			//destructor
			virtual ~AdministrationFacility() {}

			//*********************************
			// Getter Setter
			//*********************************
			virtual std::string getAdminDept() const  = 0;
			virtual void setAdminDept(std::string _adminDept) = 0;
			virtual const std::shared_ptr<Bag<ClinicModel::Staff>>& getAdmins() const  = 0;
			
			
			
			//*********************************
			// Operations
			//*********************************
			//Methods defined by Operations
			virtual void createAdmin(std::shared_ptr<ClinicModel::Staff> staff)  = 0;
			virtual void removeAdmin(std::shared_ptr<ClinicModel::Staff> staff)  = 0;


		protected:
			//*********************************
			// Members
			//*********************************
			std::string m_adminDept;
			mutable std::shared_ptr<Bag<ClinicModel::Staff>> m_admins;
			
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			
	};
}
#endif /* end of include guard: CLINICMODEL_ADMINISTRATIONFACILITY__HPP */
