//********************************************************************
//*    	
//* Warning: This file was generated by MDE4CPP Generator
//*
//********************************************************************

#ifndef CLINICMODEL_FACTORY_HPP
#define CLINICMODEL_FACTORY_HPP

#include "uml/Factory.hpp"
#include "ClinicModel/ClinicModelPackage.hpp"

namespace ClinicModel
{
	class AdministrationFacility;
	class Clinic;
	class Facility;
	class GeneralFacility;
	class SpecializedFacility;
	class Staff;
}

namespace ClinicModel 
{
	class ClinicModelPackage;
	class ClinicModelFactory;

	class ClinicModelFactory : virtual public uml::Factory 
	{ 
		protected:
			//protected default construcotr
			ClinicModelFactory(){}

			//Singleton Getter
			public:
				static std::shared_ptr<ClinicModelFactory> eInstance();

			//Creator functions
			virtual std::shared_ptr<uml::Element> create(const unsigned int _metaClassId,  std::shared_ptr<uml::Element> container= nullptr, const unsigned int referenceID = -1) const = 0;
			virtual std::shared_ptr<uml::Element> create(const std::shared_ptr<uml::Class> _class,  std::shared_ptr<uml::Element> container= nullptr, const unsigned int referenceID = -1) const = 0;
			virtual std::shared_ptr<uml::Element> create(const std::string _className,  std::shared_ptr<uml::Element> container= nullptr, const unsigned int referenceID = -1) const = 0;

			//START Create methods for class AdministrationFacility
			virtual std::shared_ptr<ClinicModel::AdministrationFacility> createAdministrationFacility(const int metaElementID = ClinicModelPackage::ADMINISTRATIONFACILITY_CLASS) const  = 0;
			virtual std::shared_ptr<ClinicModel::AdministrationFacility> createAdministrationFacility_as_employAdmins_in_Clinic(std::shared_ptr<ClinicModel::Clinic> par_clinics, const int metaElementID = ClinicModelPackage::ADMINISTRATIONFACILITY_CLASS) const  = 0 ; 
			//END Create methods for class AdministrationFacility
			
			//START Create methods for class Clinic
			virtual std::shared_ptr<ClinicModel::Clinic> createClinic(const int metaElementID = ClinicModelPackage::CLINIC_CLASS) const  = 0;
			//END Create methods for class Clinic
			
			//START Create methods for class GeneralFacility
			virtual std::shared_ptr<ClinicModel::GeneralFacility> createGeneralFacility(const int metaElementID = ClinicModelPackage::GENERALFACILITY_CLASS) const  = 0;
			virtual std::shared_ptr<ClinicModel::GeneralFacility> createGeneralFacility_as_generalfacilities_in_Clinic(std::shared_ptr<ClinicModel::Clinic> par_clinics, const int metaElementID = ClinicModelPackage::GENERALFACILITY_CLASS) const  = 0 ; 
			//END Create methods for class GeneralFacility
			
			//START Create methods for class SpecializedFacility
			virtual std::shared_ptr<ClinicModel::SpecializedFacility> createSpecializedFacility(const int metaElementID = ClinicModelPackage::SPECIALIZEDFACILITY_CLASS) const  = 0;
			virtual std::shared_ptr<ClinicModel::SpecializedFacility> createSpecializedFacility_as_specialfacilities_in_Clinic(std::shared_ptr<ClinicModel::Clinic> par_clinics, const int metaElementID = ClinicModelPackage::SPECIALIZEDFACILITY_CLASS) const  = 0 ; 
			//END Create methods for class SpecializedFacility
			
			//START Create methods for class Staff
			virtual std::shared_ptr<ClinicModel::Staff> createStaff(const int metaElementID = ClinicModelPackage::STAFF_CLASS) const  = 0;
			virtual std::shared_ptr<ClinicModel::Staff> createStaff_as_admins_in_AdministrationFacility(std::shared_ptr<ClinicModel::AdministrationFacility> par_administrationfacility, const int metaElementID = ClinicModelPackage::STAFF_CLASS) const  = 0 ; 
			virtual std::shared_ptr<ClinicModel::Staff> createStaff_as_doctors_in_SpecializedFacility(std::shared_ptr<ClinicModel::SpecializedFacility> par_getAssigned, const int metaElementID = ClinicModelPackage::STAFF_CLASS) const  = 0 ; 
			virtual std::shared_ptr<ClinicModel::Staff> createStaff_as_nurses_in_GeneralFacility(std::shared_ptr<ClinicModel::GeneralFacility> par_hasShift, const int metaElementID = ClinicModelPackage::STAFF_CLASS) const  = 0 ; 
			virtual std::shared_ptr<ClinicModel::Staff> createStaff_as_staffs_in_Clinic(std::shared_ptr<ClinicModel::Clinic> par_clinics, const int metaElementID = ClinicModelPackage::STAFF_CLASS) const  = 0 ; 
			//END Create methods for class Staff
			
			
			//Package
			virtual std::shared_ptr<ClinicModelPackage> getClinicModelPackage() = 0;
	};
}
#endif /* end of include guard: CLINICMODEL_FACTORY_HPP */
