//********************************************************************
//*    	
//* Warning: This file was generated by MDE4CPP Generator
//*
//********************************************************************

#ifndef CLINICMODEL_CLINIC__HPP
#define CLINICMODEL_CLINIC__HPP

template<class T> class Bag;



//Forward declarations for used types
namespace ClinicModel 
{
	class Staff;
	class GeneralFacility;
	class AdministrationFacility;
	class SpecializedFacility;
}
namespace ClinicModel 
{
	class Staff;
	class GeneralFacility;
	class AdministrationFacility;
	class SpecializedFacility;
}
namespace ClinicModel 
{
	class Staff;
	class GeneralFacility;
	class AdministrationFacility;
	class SpecializedFacility;
}
namespace ClinicModel 
{
	class Staff;
	class GeneralFacility;
	class AdministrationFacility;
	class SpecializedFacility;
}

// base class includes
#include "uml/Element.hpp"



namespace ClinicModel
{
	class Clinic : virtual public uml::Element 
	{
		protected:
			Clinic(){}

		public:
			//destructor
			virtual ~Clinic() {}

			//*********************************
			// Getter Setter
			//*********************************
			virtual std::string getAddress() const  = 0;
			virtual void setAddress(std::string _address) = 0;
			virtual std::string getClinicName() const  = 0;
			virtual void setClinicName(std::string _clinicName) = 0;
			virtual const std::shared_ptr<Bag<ClinicModel::AdministrationFacility>>& getEmployAdmins() const  = 0;
			virtual const std::shared_ptr<Bag<ClinicModel::GeneralFacility>>& getGeneralfacilities() const  = 0;
			virtual const std::shared_ptr<Bag<ClinicModel::SpecializedFacility>>& getSpecialfacilities() const  = 0;
			virtual const std::shared_ptr<Bag<ClinicModel::Staff>>& getStaffs() const  = 0;
			
			
			
			//*********************************
			// Operations
			//*********************************
			//Methods defined by Operations
			virtual void changeDoctorFacility(std::shared_ptr<ClinicModel::Staff> staff, std::string specialFaciltylocation, std::string specializationType)  = 0;
			virtual void changeNurseFacility(std::shared_ptr<ClinicModel::Staff> staff, std::string generalFaciltylocation)  = 0;
			virtual void coordinateAdmin(std::shared_ptr<ClinicModel::Staff> staff, std::string adminDepartment, std::string adminFacilitylocation)  = 0;
			virtual void printClinicDetails()  = 0;


		protected:
			//*********************************
			// Members
			//*********************************
			std::string m_address;
			std::string m_clinicName;
			mutable std::shared_ptr<Bag<ClinicModel::AdministrationFacility>> m_employAdmins;
			mutable std::shared_ptr<Bag<ClinicModel::GeneralFacility>> m_generalfacilities;
			mutable std::shared_ptr<Bag<ClinicModel::SpecializedFacility>> m_specialfacilities;
			mutable std::shared_ptr<Bag<ClinicModel::Staff>> m_staffs;
			
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			
	};
}
#endif /* end of include guard: CLINICMODEL_CLINIC__HPP */
