//********************************************************************
//*    	
//* Warning: This file was generated by MDE4CPP Generator
//*
//********************************************************************

#ifndef CLINICMODEL_METAMODELPACKAGE_HPP
#define CLINICMODEL_METAMODELPACKAGE_HPP
#include "uml/Model.hpp"

namespace uml 
{
	class Association;
	class Class;
	class FunctionBehavior;
	class Operation;
	class Parameter;
	class Property;
}


namespace ClinicModel 
{
	/*!
	The Metamodel Package for the ClinicModel metamodel. This package is used to enable the reflection of model elements. It contains all model elements
	which were described in an ecore file.
	*/
	class ClinicModelPackage : virtual public uml::Model
	{
		//protected default construcotr
		protected:
			ClinicModelPackage(){}

		public:
			//static variables
			static const std::string eNAME;
			static const std::string eNS_URI;
			static const std::string eNS_PREFIX;

			//getter for the ownedMember
			virtual const std::shared_ptr<uml::Association>& get_A_ClinicModel_Staff_admins_administrationFacility() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_A_ClinicModel_Staff_admins_administrationFacility_Property2() = 0;  
			virtual const std::shared_ptr<uml::Association>& get_A_ClinicModel_Staff_doctors_specializedFacility() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_A_ClinicModel_Staff_doctors_specializedFacility_Property1() = 0;  
			virtual const std::shared_ptr<uml::Association>& get_A_ClinicModel_Staff_nurses_generalFacility() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_A_ClinicModel_Staff_nurses_generalFacility_Property2() = 0;  
			virtual const std::shared_ptr<uml::Association>& get_A_clinic_ClinicModel_AdministrationFacility_employAdmins() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_A_clinic_ClinicModel_AdministrationFacility_employAdmins_Property1() = 0;  
			virtual const std::shared_ptr<uml::Association>& get_A_clinic_ClinicModel_GeneralFacility_generalfacilities() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_A_clinic_ClinicModel_GeneralFacility_generalfacilities_Property1() = 0;  
			virtual const std::shared_ptr<uml::Association>& get_A_clinic_ClinicModel_SpecializedFacility_specialfacilities() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_A_clinic_ClinicModel_SpecializedFacility_specialfacilities_Property1() = 0;  
			virtual const std::shared_ptr<uml::Association>& get_A_clinic_ClinicModel_Staff_staffs() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_A_clinic_ClinicModel_Staff_staffs_Property1() = 0;  
			virtual const std::shared_ptr<uml::Class>& get_ClinicModel_AdministrationFacility() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_AdministrationFacility_adminDept() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_AdministrationFacility_admins() = 0;  
			virtual const std::shared_ptr<uml::FunctionBehavior>& get_ClinicModel_AdministrationFacility_createAdmin() = 0;  
			virtual const std::shared_ptr<uml::Operation>& get_ClinicModel_AdministrationFacility_createAdmin_Staff_Staff() = 0;  
			virtual const std::shared_ptr<uml::Parameter>& get_ClinicModel_AdministrationFacility_createAdmin_Staff_Staff_staff() = 0;  
			virtual const std::shared_ptr<uml::FunctionBehavior>& get_ClinicModel_AdministrationFacility_removeAdmin() = 0;  
			virtual const std::shared_ptr<uml::Operation>& get_ClinicModel_AdministrationFacility_removeAdmin_Staff_Staff() = 0;  
			virtual const std::shared_ptr<uml::Parameter>& get_ClinicModel_AdministrationFacility_removeAdmin_Staff_Staff_staff() = 0;  
			virtual const std::shared_ptr<uml::Class>& get_ClinicModel_Clinic() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_Clinic_address() = 0;  
			virtual const std::shared_ptr<uml::FunctionBehavior>& get_ClinicModel_Clinic_changeDoctorFacility() = 0;  
			virtual const std::shared_ptr<uml::Operation>& get_ClinicModel_Clinic_changeDoctorFacility_Staff_String_String_Staff_String_String() = 0;  
			virtual const std::shared_ptr<uml::Parameter>& get_ClinicModel_Clinic_changeDoctorFacility_Staff_String_String_Staff_String_String_specialFaciltylocation() = 0;  
			virtual const std::shared_ptr<uml::Parameter>& get_ClinicModel_Clinic_changeDoctorFacility_Staff_String_String_Staff_String_String_specializationType() = 0;  
			virtual const std::shared_ptr<uml::Parameter>& get_ClinicModel_Clinic_changeDoctorFacility_Staff_String_String_Staff_String_String_staff() = 0;  
			virtual const std::shared_ptr<uml::FunctionBehavior>& get_ClinicModel_Clinic_changeNurseFacility() = 0;  
			virtual const std::shared_ptr<uml::Operation>& get_ClinicModel_Clinic_changeNurseFacility_Staff_String_Staff_String() = 0;  
			virtual const std::shared_ptr<uml::Parameter>& get_ClinicModel_Clinic_changeNurseFacility_Staff_String_Staff_String_generalFaciltylocation() = 0;  
			virtual const std::shared_ptr<uml::Parameter>& get_ClinicModel_Clinic_changeNurseFacility_Staff_String_Staff_String_staff() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_Clinic_clinicName() = 0;  
			virtual const std::shared_ptr<uml::FunctionBehavior>& get_ClinicModel_Clinic_coordinateAdmin() = 0;  
			virtual const std::shared_ptr<uml::Operation>& get_ClinicModel_Clinic_coordinateAdmin_Staff_String_String_Staff_String_String() = 0;  
			virtual const std::shared_ptr<uml::Parameter>& get_ClinicModel_Clinic_coordinateAdmin_Staff_String_String_Staff_String_String_adminDepartment() = 0;  
			virtual const std::shared_ptr<uml::Parameter>& get_ClinicModel_Clinic_coordinateAdmin_Staff_String_String_Staff_String_String_adminFacilitylocation() = 0;  
			virtual const std::shared_ptr<uml::Parameter>& get_ClinicModel_Clinic_coordinateAdmin_Staff_String_String_Staff_String_String_staff() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_Clinic_employAdmins() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_Clinic_generalfacilities() = 0;  
			virtual const std::shared_ptr<uml::FunctionBehavior>& get_ClinicModel_Clinic_printClinicDetails() = 0;  
			virtual const std::shared_ptr<uml::Operation>& get_ClinicModel_Clinic_printClinicDetails__() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_Clinic_specialfacilities() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_Clinic_staffs() = 0;  
			virtual const std::shared_ptr<uml::Class>& get_ClinicModel_Facility() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_Facility_address() = 0;  
			virtual const std::shared_ptr<uml::Class>& get_ClinicModel_GeneralFacility() = 0;  
			virtual const std::shared_ptr<uml::FunctionBehavior>& get_ClinicModel_GeneralFacility_assignNurse() = 0;  
			virtual const std::shared_ptr<uml::Operation>& get_ClinicModel_GeneralFacility_assignNurse_Staff_Staff() = 0;  
			virtual const std::shared_ptr<uml::Parameter>& get_ClinicModel_GeneralFacility_assignNurse_Staff_Staff_staff() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_GeneralFacility_nurses() = 0;  
			virtual const std::shared_ptr<uml::FunctionBehavior>& get_ClinicModel_GeneralFacility_releaseNurse() = 0;  
			virtual const std::shared_ptr<uml::Operation>& get_ClinicModel_GeneralFacility_releaseNurse_Staff_Staff() = 0;  
			virtual const std::shared_ptr<uml::Parameter>& get_ClinicModel_GeneralFacility_releaseNurse_Staff_Staff_staff() = 0;  
			virtual const std::shared_ptr<uml::Class>& get_ClinicModel_SpecializedFacility() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_SpecializedFacility_doctors() = 0;  
			virtual const std::shared_ptr<uml::FunctionBehavior>& get_ClinicModel_SpecializedFacility_excludeDoctor() = 0;  
			virtual const std::shared_ptr<uml::Operation>& get_ClinicModel_SpecializedFacility_excludeDoctor_Staff_Staff() = 0;  
			virtual const std::shared_ptr<uml::Parameter>& get_ClinicModel_SpecializedFacility_excludeDoctor_Staff_Staff_staff() = 0;  
			virtual const std::shared_ptr<uml::FunctionBehavior>& get_ClinicModel_SpecializedFacility_includeDoctor() = 0;  
			virtual const std::shared_ptr<uml::Operation>& get_ClinicModel_SpecializedFacility_includeDoctor_Staff_Staff() = 0;  
			virtual const std::shared_ptr<uml::Parameter>& get_ClinicModel_SpecializedFacility_includeDoctor_Staff_Staff_staff() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_SpecializedFacility_specialization() = 0;  
			virtual const std::shared_ptr<uml::Class>& get_ClinicModel_Staff() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_Staff_department() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_Staff_name() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_Staff_role() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_Staff_specialty() = 0;  
			virtual const std::shared_ptr<uml::Property>& get_ClinicModel_Staff_ward() = 0;  
			virtual const std::shared_ptr<uml::FunctionBehavior>& get_ClinicModel_mainProgram() = 0;  
			
			
			

			//getter for subPackages

			//Singleton Getter
			public:
				static std::shared_ptr<ClinicModelPackage> eInstance();

			//Static IDs
			//Class ClinicModel::AdministrationFacility
			static const unsigned long ADMINISTRATIONFACILITY_CLASS = 1185759508;
			static const unsigned int ADMINISTRATIONFACILITY_CLASS_FEATURE_COUNT = 5;
			static const unsigned int ADMINISTRATIONFACILITY_CLASS_OPERATION_COUNT = 2;
			//Properties
			static const unsigned long ADMINISTRATIONFACILITY_PROPERTY_ADMINDEPT = 659176191;
			static const unsigned long ADMINISTRATIONFACILITY_PROPERTY_ADMINS = 490070260;
			//Properties from compositions
			static const unsigned long EMPLOYADMINS_CLINICS = 809351423;
			//Operations
			//ClinicModel::AdministrationFacility::createAdmin(ClinicModel::Staff)
			static const unsigned long ADMINISTRATIONFACILITY_OPERATION_CREATEADMIN_STAFF = 1758725820;
			//ClinicModel::AdministrationFacility::removeAdmin(ClinicModel::Staff)
			static const unsigned long ADMINISTRATIONFACILITY_OPERATION_REMOVEADMIN_STAFF = 1756317685;
			//Behaviors
				//FunctionBehavior ClinicModel::AdministrationFacility::createAdmin
			static const unsigned long ADMINISTRATIONFACILITY_FUNCTIONBEHAVIOR_CREATEADMIN = 276818402;
			static const unsigned int ADMINISTRATIONFACILITY_FUNCTIONBEHAVIOR_CREATEADMIN_FEATURE_COUNT = 0;
			static const unsigned int ADMINISTRATIONFACILITY_FUNCTIONBEHAVIOR_CREATEADMIN_OPERATION_COUNT = 0;
			
				//FunctionBehavior ClinicModel::AdministrationFacility::removeAdmin
				static const unsigned long ADMINISTRATIONFACILITY_FUNCTIONBEHAVIOR_REMOVEADMIN = 274410267;
				static const unsigned int ADMINISTRATIONFACILITY_FUNCTIONBEHAVIOR_REMOVEADMIN_FEATURE_COUNT = 0;
				static const unsigned int ADMINISTRATIONFACILITY_FUNCTIONBEHAVIOR_REMOVEADMIN_OPERATION_COUNT = 0;
				
			
			//Class ClinicModel::Clinic
			static const unsigned long CLINIC_CLASS = 964187712;
			static const unsigned int CLINIC_CLASS_FEATURE_COUNT = 10;
			static const unsigned int CLINIC_CLASS_OPERATION_COUNT = 4;
			//Properties
			static const unsigned long CLINIC_PROPERTY_CLINICNAME = 631390961;
			static const unsigned long CLINIC_PROPERTY_ADDRESS = 702870711;
			static const unsigned long CLINIC_PROPERTY_GENERALFACILITIES = 1359947364;
			static const unsigned long CLINIC_PROPERTY_STAFFS = 1590676663;
			static const unsigned long CLINIC_PROPERTY_EMPLOYADMINS = 1643195785;
			static const unsigned long CLINIC_PROPERTY_SPECIALFACILITIES = 64986256;
			//Operations
			//ClinicModel::Clinic::changeDoctorFacility(ClinicModel::Staff, std::string, std::string)
			static const unsigned long CLINIC_OPERATION_CHANGEDOCTORFACILITY_STAFF_STRING = 1768765072;
			//ClinicModel::Clinic::changeNurseFacility(ClinicModel::Staff, std::string)
			static const unsigned long CLINIC_OPERATION_CHANGENURSEFACILITY_STAFF_STRING = 1832867374;
			//ClinicModel::Clinic::printClinicDetails()
			static const unsigned long CLINIC_OPERATION_PRINTCLINICDETAILS = 557477294;
			//ClinicModel::Clinic::coordinateAdmin(ClinicModel::Staff, std::string, std::string)
			static const unsigned long CLINIC_OPERATION_COORDINATEADMIN_STAFF_STRING = 992000903;
			//Behaviors
				//FunctionBehavior ClinicModel::Clinic::coordinateAdmin
			static const unsigned long CLINIC_FUNCTIONBEHAVIOR_COORDINATEADMIN = 164616585;
			static const unsigned int CLINIC_FUNCTIONBEHAVIOR_COORDINATEADMIN_FEATURE_COUNT = 0;
			static const unsigned int CLINIC_FUNCTIONBEHAVIOR_COORDINATEADMIN_OPERATION_COUNT = 0;
			
				//FunctionBehavior ClinicModel::Clinic::changeNurseFacility
				static const unsigned long CLINIC_FUNCTIONBEHAVIOR_CHANGENURSEFACILITY = 643963140;
				static const unsigned int CLINIC_FUNCTIONBEHAVIOR_CHANGENURSEFACILITY_FEATURE_COUNT = 0;
				static const unsigned int CLINIC_FUNCTIONBEHAVIOR_CHANGENURSEFACILITY_OPERATION_COUNT = 0;
				
				//FunctionBehavior ClinicModel::Clinic::printClinicDetails
				static const unsigned long CLINIC_FUNCTIONBEHAVIOR_PRINTCLINICDETAILS = 1999333173;
				static const unsigned int CLINIC_FUNCTIONBEHAVIOR_PRINTCLINICDETAILS_FEATURE_COUNT = 0;
				static const unsigned int CLINIC_FUNCTIONBEHAVIOR_PRINTCLINICDETAILS_OPERATION_COUNT = 0;
				
				//FunctionBehavior ClinicModel::Clinic::changeDoctorFacility
				static const unsigned long CLINIC_FUNCTIONBEHAVIOR_CHANGEDOCTORFACILITY = 330060609;
				static const unsigned int CLINIC_FUNCTIONBEHAVIOR_CHANGEDOCTORFACILITY_FEATURE_COUNT = 0;
				static const unsigned int CLINIC_FUNCTIONBEHAVIOR_CHANGEDOCTORFACILITY_OPERATION_COUNT = 0;
				
			
			//Class ClinicModel::Facility
			static const unsigned long FACILITY_CLASS = 716373363;
			static const unsigned int FACILITY_CLASS_FEATURE_COUNT = 1;
			static const unsigned int FACILITY_CLASS_OPERATION_COUNT = 0;
			//Properties
			static const unsigned long FACILITY_PROPERTY_ADDRESS = 1116324828;
			
			//Class ClinicModel::GeneralFacility
			static const unsigned long GENERALFACILITY_CLASS = 1476153249;
			static const unsigned int GENERALFACILITY_CLASS_FEATURE_COUNT = 4;
			static const unsigned int GENERALFACILITY_CLASS_OPERATION_COUNT = 2;
			//Properties
			static const unsigned long GENERALFACILITY_PROPERTY_NURSES = 529041091;
			//Properties from compositions
			static const unsigned long GENERALFACILITIES_CLINICS = 1155704638;
			//Operations
			//ClinicModel::GeneralFacility::assignNurse(ClinicModel::Staff)
			static const unsigned long GENERALFACILITY_OPERATION_ASSIGNNURSE_STAFF = 1641656218;
			//ClinicModel::GeneralFacility::releaseNurse(ClinicModel::Staff)
			static const unsigned long GENERALFACILITY_OPERATION_RELEASENURSE_STAFF = 406694734;
			//Behaviors
				//FunctionBehavior ClinicModel::GeneralFacility::releaseNurse
			static const unsigned long GENERALFACILITY_FUNCTIONBEHAVIOR_RELEASENURSE = 1243729722;
			static const unsigned int GENERALFACILITY_FUNCTIONBEHAVIOR_RELEASENURSE_FEATURE_COUNT = 0;
			static const unsigned int GENERALFACILITY_FUNCTIONBEHAVIOR_RELEASENURSE_OPERATION_COUNT = 0;
			
				//FunctionBehavior ClinicModel::GeneralFacility::assignNurse
				static const unsigned long GENERALFACILITY_FUNCTIONBEHAVIOR_ASSIGNNURSE = 1981597806;
				static const unsigned int GENERALFACILITY_FUNCTIONBEHAVIOR_ASSIGNNURSE_FEATURE_COUNT = 0;
				static const unsigned int GENERALFACILITY_FUNCTIONBEHAVIOR_ASSIGNNURSE_OPERATION_COUNT = 0;
				
			
			//Class ClinicModel::SpecializedFacility
			static const unsigned long SPECIALIZEDFACILITY_CLASS = 773078824;
			static const unsigned int SPECIALIZEDFACILITY_CLASS_FEATURE_COUNT = 5;
			static const unsigned int SPECIALIZEDFACILITY_CLASS_OPERATION_COUNT = 2;
			//Properties
			static const unsigned long SPECIALIZEDFACILITY_PROPERTY_SPECIALIZATION = 482341554;
			static const unsigned long SPECIALIZEDFACILITY_PROPERTY_DOCTORS = 245173943;
			//Properties from compositions
			static const unsigned long SPECIALFACILITIES_CLINICS = 1084367869;
			//Operations
			//ClinicModel::SpecializedFacility::includeDoctor(ClinicModel::Staff)
			static const unsigned long SPECIALIZEDFACILITY_OPERATION_INCLUDEDOCTOR_STAFF = 2025791950;
			//ClinicModel::SpecializedFacility::excludeDoctor(ClinicModel::Staff)
			static const unsigned long SPECIALIZEDFACILITY_OPERATION_EXCLUDEDOCTOR_STAFF = 256021830;
			//Behaviors
				//FunctionBehavior ClinicModel::SpecializedFacility::excludeDoctor
			static const unsigned long SPECIALIZEDFACILITY_FUNCTIONBEHAVIOR_EXCLUDEDOCTOR = 1443618094;
			static const unsigned int SPECIALIZEDFACILITY_FUNCTIONBEHAVIOR_EXCLUDEDOCTOR_FEATURE_COUNT = 0;
			static const unsigned int SPECIALIZEDFACILITY_FUNCTIONBEHAVIOR_EXCLUDEDOCTOR_OPERATION_COUNT = 0;
			
				//FunctionBehavior ClinicModel::SpecializedFacility::includeDoctor
				static const unsigned long SPECIALIZEDFACILITY_FUNCTIONBEHAVIOR_INCLUDEDOCTOR = 1065904567;
				static const unsigned int SPECIALIZEDFACILITY_FUNCTIONBEHAVIOR_INCLUDEDOCTOR_FEATURE_COUNT = 0;
				static const unsigned int SPECIALIZEDFACILITY_FUNCTIONBEHAVIOR_INCLUDEDOCTOR_OPERATION_COUNT = 0;
				
			
			//Class ClinicModel::Staff
			static const unsigned long STAFF_CLASS = 772074385;
			static const unsigned int STAFF_CLASS_FEATURE_COUNT = 5;
			static const unsigned int STAFF_CLASS_OPERATION_COUNT = 0;
			//Properties
			static const unsigned long STAFF_PROPERTY_NAME = 223960033;
			static const unsigned long STAFF_PROPERTY_ROLE = 1359001430;
			static const unsigned long STAFF_PROPERTY_WARD = 1392949717;
			static const unsigned long STAFF_PROPERTY_SPECIALTY = 1560148911;
			static const unsigned long STAFF_PROPERTY_DEPARTMENT = 80305014;
			//Properties from compositions
			static const unsigned long ADMINS_ADMINISTRATIONFACILITY = 1740699712;
			static const unsigned long DOCTORS_GETASSIGNED = 976728310;
			static const unsigned long NURSES_HASSHIFT = 1804868701;
			static const unsigned long STAFFS_CLINICS = 628898873;
			
			//FunctionBehavior ClinicModel::mainProgram
			static const unsigned long CLINICMODEL_FUNCTIONBEHAVIOR_MAINPROGRAM = 1750597556;
			static const unsigned int CLINICMODEL_FUNCTIONBEHAVIOR_MAINPROGRAM_FEATURE_COUNT = 0;
			static const unsigned int CLINICMODEL_FUNCTIONBEHAVIOR_MAINPROGRAM_OPERATION_COUNT = 0;
			
			
			
	};
}
#endif /* end of include guard: CLINICMODEL_METAMODELPACKAGE_HPP */
