//********************************************************************
//*    	
//* Warning: This file was generated by MDE4CPP Generator
//*
//********************************************************************

#ifndef CLINICMODEL_FACILITY__HPP
#define CLINICMODEL_FACILITY__HPP





// base class includes
#include "uml/Element.hpp"



namespace ClinicModel
{
	class Facility : virtual public uml::Element 
	{
		protected:
			Facility(){}

		public:
			//destructor
			virtual ~Facility() {}

			//*********************************
			// Getter Setter
			//*********************************
			virtual std::string getAddress() const  = 0;
			virtual void setAddress(std::string _address) = 0;
			
			
			
			//*********************************
			// Operations
			//*********************************

		protected:
			//*********************************
			// Members
			//*********************************
			std::string m_address;
			
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			
	};
}
#endif /* end of include guard: CLINICMODEL_FACILITY__HPP */
