//********************************************************************
//*    	
//* Warning: This file was generated by MDE4CPP Generator
//*
//********************************************************************

#ifndef CLINICMODEL_GENERALFACILITY__HPP
#define CLINICMODEL_GENERALFACILITY__HPP

template<class T> class Bag;



//Forward declarations for used types
namespace ClinicModel 
{
	class Staff;
}

// base class includes
#include "ClinicModel/Facility.hpp"



namespace ClinicModel
{
	class GeneralFacility:virtual public Facility	{
		protected:
			GeneralFacility(){}

		public:
			//destructor
			virtual ~GeneralFacility() {}

			//*********************************
			// Getter Setter
			//*********************************
			virtual const std::shared_ptr<Bag<ClinicModel::Staff>>& getNurses() const  = 0;
			
			
			
			//*********************************
			// Operations
			//*********************************
			//Methods defined by Operations
			virtual void assignNurse(std::shared_ptr<ClinicModel::Staff> staff)  = 0;
			virtual void releaseNurse(std::shared_ptr<ClinicModel::Staff> staff)  = 0;


		protected:
			//*********************************
			// Members
			//*********************************
			mutable std::shared_ptr<Bag<ClinicModel::Staff>> m_nurses;
			
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			
	};
}
#endif /* end of include guard: CLINICMODEL_GENERALFACILITY__HPP */
