//********************************************************************
//*    	
//* Warning: This file was generated by MDE4CPP Generator
//*
//********************************************************************

#ifndef CLINICMODEL_SPECIALIZEDFACILITY__HPP
#define CLINICMODEL_SPECIALIZEDFACILITY__HPP

template<class T> class Bag;



//Forward declarations for used types
namespace ClinicModel 
{
	class Staff;
}

// base class includes
#include "ClinicModel/Facility.hpp"



namespace ClinicModel
{
	class SpecializedFacility:virtual public Facility	{
		protected:
			SpecializedFacility(){}

		public:
			//destructor
			virtual ~SpecializedFacility() {}

			//*********************************
			// Getter Setter
			//*********************************
			virtual const std::shared_ptr<Bag<ClinicModel::Staff>>& getDoctors() const  = 0;
			virtual std::string getSpecialization() const  = 0;
			virtual void setSpecialization(std::string _specialization) = 0;
			
			
			
			//*********************************
			// Operations
			//*********************************
			//Methods defined by Operations
			virtual void excludeDoctor(std::shared_ptr<ClinicModel::Staff> staff)  = 0;
			virtual void includeDoctor(std::shared_ptr<ClinicModel::Staff> staff)  = 0;


		protected:
			//*********************************
			// Members
			//*********************************
			mutable std::shared_ptr<Bag<ClinicModel::Staff>> m_doctors;
			std::string m_specialization;
			
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			
	};
}
#endif /* end of include guard: CLINICMODEL_SPECIALIZEDFACILITY__HPP */
