//********************************************************************
//*    	
//* Warning: This file was generated by MDE4CPP Generator
//*
//********************************************************************

#ifndef CLINICMODEL_STAFF__HPP
#define CLINICMODEL_STAFF__HPP





// base class includes
#include "uml/Element.hpp"



namespace ClinicModel
{
	class Staff : virtual public uml::Element 
	{
		protected:
			Staff(){}

		public:
			//destructor
			virtual ~Staff() {}

			//*********************************
			// Getter Setter
			//*********************************
			virtual std::string getDepartment() const  = 0;
			virtual void setDepartment(std::string _department) = 0;
			virtual std::string getName() const  = 0;
			virtual void setName(std::string _name) = 0;
			virtual std::string getRole() const  = 0;
			virtual void setRole(std::string _role) = 0;
			virtual std::string getSpecialty() const  = 0;
			virtual void setSpecialty(std::string _specialty) = 0;
			virtual std::string getWard() const  = 0;
			virtual void setWard(std::string _ward) = 0;
			
			
			
			//*********************************
			// Operations
			//*********************************

		protected:
			//*********************************
			// Members
			//*********************************
			std::string m_department;
			std::string m_name;
			std::string m_role;
			std::string m_specialty;
			std::string m_ward;
			
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			
	};
}
#endif /* end of include guard: CLINICMODEL_STAFF__HPP */
